"""
Django settings for Django_RequsetSyatem project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!f&jtbqr%1_kse$(2&ajd_)0s62cru(s8z1@-ad9^(pw&y21#f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'captcha',
    'django_crontab',
    'notifications',
    'ckeditor',
    'mptt',
    'Login',
    'Notice',
    'RequstAnswer',
    'Comment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Django_RequsetSyatem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django_RequsetSyatem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
# 项目静态文件的配置
STATICFILES_DIRS = [
                os.path.join(BASE_DIR,"statics"),
]
# Host
ALLOWED_HOSTS = ['172.16.11.218', '0.0.0.0']
APPEND_SLASH=False
AUTH_USER_MODEL = "Login.LoginUser"

MEDIA_ROOT= os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

CKEDITOR_CONFIGS = {
        # django-ckeditor默认使用default配置
        'default': {
        # 编辑器宽度自适应
            'width':'auto',
            'height':'250px',
            # tab键转换空格数
            'tabSpaces': 4,
            # 工具栏风格
            'toolbar': 'Custom',
             # 工具栏按钮
            'toolbar_Custom': [
                        # 表情 代码块
                        ['Smiley', 'CodeSnippet'], 
                        # 字体风格
                        ['Bold', 'Italic', 'Underline', 'RemoveFormat', 'Blockquote'],
                        # 字体颜色
                        ['TextColor', 'BGColor'],
                        # 链接
                        ['Link', 'Unlink'],
                        # 列表
                        ['NumberedList', 'BulletedList'],
                        # 最大化
                        ['Maximize']
                    ],
            # 加入代码块插件
            'extraPlugins': ','.join(['codesnippet']),
            }
}


CRONJOBS = [
('58 * * * *', 'RequstAnswer.ScheduledTask.MakeDate', '>>'+os.path.join(BASE_DIR, 'RequstAnswer/task.log')),]
