# Generated by Django 2.2 on 2021-02-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('RequestNumber', models.AutoField(primary_key=True, serialize=False)),
                ('RequestType', models.CharField(choices=[('RNAseq', 'RNAseq'), ('WES', 'WES'), ('SingleCell', 'SingleCell'), ('MetaGenmics', 'MetaGenmics'), ('个性化分析', '个性化分析'), ('遗传咨询', '遗传咨询'), ('其他', '其他')], default='已预约', max_length=32)),
                ('RequestUser', models.CharField(max_length=10)),
                ('RequestEmail', models.CharField(max_length=256)),
                ('RequestDate', models.DateTimeField(auto_now_add=True)),
                ('RequestTarget', models.CharField(max_length=10)),
                ('RequestContent', models.TextField(blank=True, verbose_name='预约内容')),
                ('RequestTargetData', models.CharField(max_length=40)),
                ('RequestStatus', models.CharField(choices=[('已预约', '已预约'), ('已确认', '已确认')], default='已预约', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RequestTargetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TargetName', models.CharField(max_length=10)),
                ('TargetData', models.CharField(max_length=10)),
                ('TargetTrueDate', models.DateField()),
                ('TargetStatus', models.CharField(choices=[('已预约', '已预约'), ('未预约', '未预约')], default='未预约', max_length=32)),
            ],
        ),
    ]
